server:
  port: 8080
spring:
  profile:
    active: prod
  application:
    name: auth-service
  datasource:
    url: ${DB_HOST}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  properties:
    hibernate:
      show_sql: true