server:
  port: 8080
spring:
  profile:
    active: prod
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://rocio-durcal.c5o0wi6wm88a.us-east-1.rds.amazonaws.com/rocio-durcal-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Sabumafu123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true