server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_HOST:jdbc:mysql://rocio-durcal.c5o0wi6wm88a.us-east-1.rds.amazonaws.com/rocio-durcal-db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:Sabumafu123}
  jpa:
    show-sql: true
  properties:
    hibernate:
      show_sql: true