server:
  port: 8080
spring:
  profile:
    active: prod
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://rodolfo-aicardi.c1wae46o69by.us-east-1.rds.amazonaws.com/rodolfo-aicardi-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Sabumafu123
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
  properties:
    hibernate:
      show_sql: true